# fly.toml app configuration file generated for blog-cms-nanovolt on 2023-11-08T13:52:36+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "blog-cms-nanovolt"
primary_region = "arn"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
