# fly.toml app configuration file generated for nanovolt-blog-api on 2023-11-25T11:53:06+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nanovolt-blog-api"
primary_region = "waw"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
