# fly.toml app configuration file generated for nanovolt-blog on 2023-11-25T15:10:49+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nanovolt-blog"
primary_region = "waw"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
